const ITEM_IMAGES = {
  item_Gauntlet: require("./ItemImage/ArcaneGauntlet_shadow.png").default,
  item_Gauntlet_s: require("./ItemImage/ArcaneGauntlet.png").default,
  item_Arch_s: require("./ItemImage/arch_shadow.png").default,
  item_Arch: require("./ItemImage/arch.png").default,
  item_Armor_s: require("./ItemImage/armor_shadow.png").default,
  item_Armor: require("./ItemImage/armor.png").default,
  item_Backhand_s: require("./ItemImage/Backhand_shadow.png").default,
  item_Backhand: require("./ItemImage/Backhand.png").default,
  item_Belt_s: require("./ItemImage/belt_shadow.png").default,
  item_Belt: require("./ItemImage/belt.png").default,
  item_Blood_shadow: require("./ItemImage/blood_shadow.png").default,
  item_Blood: require("./ItemImage/blood.png").default,
  item_BlueBuff_s: require("./ItemImage/BlueBuff_shadow.png").default,
  item_BlueBuff: require("./ItemImage/BlueBuff.png").default,
  item_Bow: require("./ItemImage/bow.png").default,
  item_BrawlersGloves: require("./ItemImage/BrawlersGloves.png").default,
  item_Cape_s: require("./ItemImage/cape_shadow.png").default,
  item_Chalice: require("./ItemImage/Chalice.png").default,
  item_Chalice_s: require("./ItemImage/ChaliceOfPower_shadow.png").default,
  item_DragonsClaw_s: require("./ItemImage/DragonsClaw_shadow.png").default,
  item_DragonsClaw: require("./ItemImage/DragonsClaw.png").default,
  item_DuelistsZeal: require("./ItemImage/DuelistsZeal.png").default,
  item_ElderwoodHeirloom: require("./ItemImage/ElderwoodHeirloom.png").default,
  item_ForceOfNature: require("./ItemImage/ForceOfNature.png").default,
  item_ForceOfNature_s: require("./ItemImage/ForceOfNature_shadow.png").default,
  item_Frozen_s: require("./ItemImage/frozen_shadow.png").default,
  item_Frozen: require("./ItemImage/frozen.png").default,
  item_Gargoylestoneplate: require("./ItemImage/gargoylestoneplate.png")
    .default,
  item_GiantSlayer_shadow: require("./ItemImage/GiantSlayer_shadow.png")
    .default,
  item_GiantSlayer: require("./ItemImage/GiantSlayer.png").default,
  item_BrawlersGloves: require("./ItemImage/BrawlersGloves.png").default,
  item_Guardian_s: require("./ItemImage/guardian_shadow.png").default,
  item_guardian: require("./ItemImage/guardian.png").default,
  item_Guinsoo_shadow: require("./ItemImage/guinsoo_shadow.png").default,
  item_Guinsoo: require("./ItemImage/guinsoo.png").default,
  item_HandofJustice_s: require("./ItemImage/HandofJustice_shadow.png").default,
  item_HandofJustice: require("./ItemImage/HandofJustice.png").default,
  item_Hextech_s: require("./ItemImage/Hextech_shadow.png").default,
  item_Hextech: require("./ItemImage/Hextech.png").default,
  item_infinity_s: require("./ItemImage/infinity_shadow.png").default,
  item_infinity: require("./ItemImage/infinity.png").default,
  item_IonicSpark_shadow: require("./ItemImage/IonicSpark_shadow.png").default,
  item_IonicSpark: require("./ItemImage/IonicSpark.png").default,
  item_IronWill: require("./ItemImage/IronWill.png").default,
  item_last_whisper_shadow: require("./ItemImage/last_whisper_shadow.png")
    .default,
  item_last_whisper: require("./ItemImage/last_whisper.png").default,
  item_IronSolari: require("./ItemImage/IronSolari.png").default,
  item_LordsEdge: require("./ItemImage/LordsEdge.png").default,
  item_LordsEdge_s: require("./ItemImage/LordsEdge_shadow.png").default,
  item_MagesCap_shadow: require("./ItemImage/MagesCap_shadow.png").default,
  item_MantleofDusk: require("./ItemImage/MantleofDusk.png").default,
  item_Morello_s: require("./ItemImage/Morello_shadow.png").default,
  item_Morello: require("./ItemImage/Morello.png").default,
  item_Quicksilver: require("./ItemImage/Quicksilver.png").default,
  item_Quicksilver_s: require("./ItemImage/Quicksilver_shadow.png").default,
  item_rabadon: require("./ItemImage/rabadon.png").default,
  item_rabadon_s: require("./ItemImage/rabadon_shadow.png").default,
  item_rapid_shadow: require("./ItemImage/rapid_shadow.png").default,
  item_rapid: require("./ItemImage/rapid.png").default,
  item_runnan_shadow: require("./ItemImage/runnan_shadow.png").default,
  item_runnan: require("./ItemImage/runnan.png").default,
  item_sacrificial_shadow: require("./ItemImage/sacrificial_shadow.png")
    .default,
  item_sacrificial: require("./ItemImage/sacrificial.png").default,
  item_DuelistsZeal_s: require("./ItemImage/DuelistsZeal_shadow.png").default,
  item_ElderwoodHeirloom_s: require("./ItemImage/ElderwoodHeirloom_shadow.png")
    .default,
  item_MagesCap_shadow: require("./ItemImage/MagesCap_shadow.png").default,
  item_MantleofDusk_shadow: require("./ItemImage/MantleofDusk_shadow.png")
    .default,
  item_SwordoftheDivine_shadow:
    require("./ItemImage/SwordoftheDivine_shadow.png").default,
  item_VanguardsCuirass_shadow:
    require("./ItemImage/VanguardsCuirass_shadow.png").default,
  item_WarlordsBanner_shadow: require("./ItemImage/WarlordsBanner_shadow.png")
    .default,
  item_shojin_s: require("./ItemImage/shojin_shadow.png").default,
  item_shojin: require("./ItemImage/shojin.png").default,
  item_Shroud: require("./ItemImage/Shroud.png").default,
  item_Shroud_s: require("./ItemImage/Shroud_shadow.png").default,
  item_Solari_s: require("./ItemImage/Solari_shadow.png").default,
  item_spatula_s: require("./ItemImage/spatula_shadow.png").default,
  item_Spatula: require("./ItemImage/Spatula.png").default,
  item_statikk_s: require("./ItemImage/statikk_shadow.png").default,
  item_statikk: require("./ItemImage/statikk.png").default,
  item_stick_s: require("./ItemImage/stick_shadow.png").default,
  item_stick: require("./ItemImage/stick.png").default,
  item_SunfireCape: require("./ItemImage/SunfireCape.png").default,
  item_SunfireCape_s: require("./ItemImage/SunfireCape_shadow.png").default,
  item_sword_s: require("./ItemImage/sword_shadow.png").default,
  item_sword: require("./ItemImage/sword.png").default,
  item_SwordoftheDivine: require("./ItemImage/SwordoftheDivine.png").default,
  item_SwordoftheDivine_s: require("./ItemImage/SwordoftheDivine_shadow.png")
    .default,
  item_tear_s: require("./ItemImage/tear_shadow.png").default,
  item_tear: require("./ItemImage/tear.png").default,
  item_ThiefsGloves: require("./ItemImage/ThiefsGloves.png").default,
  item_ThiefsGloves_s: require("./ItemImage/ThiefsGloves_shadow.png").default,
  item_TitansResolve_shadow: require("./ItemImage/TitansResolve_shadow.png")
    .default,
  item_VanguardsCuirass: require("./ItemImage/VanguardsCuirass.png").default,
  item_VanguardsCuirass_s: require("./ItemImage/VanguardsCuirass_shadow.png")
    .default,
  item_vest: require("./ItemImage/vest.png").default,
  item_vest_shadow: require("./ItemImage/vest_shadow.png").default,
  item_WarlordsBanner: require("./ItemImage/WarlordsBanner.png").default,
  item_WarlordsBanner_s: require("./ItemImage/WarlordsBanner_shadow.png")
    .default,
  item_warmog: require("./ItemImage/warmog.png").default,
  item_warmog_s: require("./ItemImage/warmog_shadow.png").default,
  item_GhostBlade_shadow: require("./ItemImage/GhostBlade_shadow.png").default,
  item_GhostBlade: require("./ItemImage/GhostBlade.png").default,
  item_ZekesHerald_shadow: require("./ItemImage/ZekesHerald_shadow.png")
    .default,
  item_ZekesHerald: require("./ItemImage/ZekesHerald.png").default,
  item_Zephyr_shadow: require("./ItemImage/Zephyr_shadow.png").default,
  item_Zephyr: require("./ItemImage/Zephyr.png").default,
  item_Zephyr_shadow: require("./ItemImage/Zephyr_shadow.png").default,
  item_Zephyr: require("./ItemImage/Zephyr.png").default,
};

export default ITEM_IMAGES;
